//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentStudy
    {
        public string StudentStudyID { get; set; }
        public string StudentID { get; set; }
        public string LecturerID { get; set; }
        public string YearStudyID { get; set; }
        public string CourseID { get; set; }
        public Nullable<long> GradeNumber { get; set; }
        public string GradeCharacter { get; set; }
    }
}
